### ISSUE TITLE
getIssues is hardcoded to open only

### ISSUE THREAD

**Issue by lukekarrys** [espy/ubersicht#26]
I'm now using this pretty much daily to look at [ampersandjs issues](http://issues.ampersandjs.com) and it is so helpful. Great work!

I noticed that inside `getIssues()` the filters are set to [only retrieve open issues](https://github.com/espy/ubersicht/blob/ff6e332a0541247a2b5265aa937a5d6e45b39d2d/script/main.js#L165). From a quick glance at the code, it looks like the `filters` could be removed since everything is fetched and then the display is filtered locally. Is that correct?

**Comment by espy** [comment]
Great to hear! Thanks for all your help with this, I'm glad it's proving useful :)
