### ISSUE TITLE
Uncaught TypeError: Cannot read property 'items' of undefined main.js:253

### ISSUE THREAD

**Issue by jmatsushita** [espy/ubersicht#30]
Hi there,

Cool project! When trying to run it on my organisation (http://espy.github.io/ubersicht/#iilab) using Chrome on OSX I get the following in the console:

```
Uncaught TypeError: Cannot read property 'items' of undefined main.js:253
  mapDataItems main.js:253
  (anonymous function) main.js:246
  (anonymous function) jquery.js:3069
  l jquery.js:2913
  c.fireWith jquery.js:3025
  k jquery.js:7400
  (anonymous function) jquery.js:7822
```

Jun

**Comment by espy** [comment]
Thanks for reporting that error, it only seems to occur with some organisations, with GitHub returning data in a different format for them than for most others. No idea why, and I'd never have noticed by myself :) 

Anyway, it's fixed now.
