### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BigBlueHat** [espy/ubersicht#31]
First and foremost, Ubersicht is lovely! Great work. :+1: 

Second, would you mind stating a license somewhere in the project? I'm assuming that's the intent (based on it being on the [Hood.ie Initiatives page](http://hood.ie/initiatives/#tools) and the "fork this" link in the header). However, without a stated license it's technically "All Right Reserved" (most places).

Would you mind clearing that up? :smiley: 

Thanks!

**Comment by janl** [comment]
https://github.com/espy/ubersicht/pull/32

**Comment by BigBlueHat** [comment]
Closed via #32.

Thanks!
