### ISSUE TITLE
Assigned User Icon links to API endpoint

### ISSUE THREAD

**Issue by simeydotme** [espy/ubersicht#34]
The hyperlink attached to the "assigned user" actually links directly to the GitHub API endpoint; 

![image](https://cloud.githubusercontent.com/assets/2817396/12148041/25fede20-b4d7-11e5-8a0e-6a01665a235c.png)

For example, clicking this user goes to: https://api.github.com/users/gr2m

---

_Example screenshot/app is: http://espy.github.io/ubersicht/?showOpen=true&showClosed=false&showCommented=true&showUncommented=true&showIssues=true&showPullRequests=false&last24Hours=false&repos=null&labels=null&milestones=null&usernames=null#hoodiehq_

I would expect the desired result is to link to the user's github account homepage?

**Comment by espy** [comment]
Second time's the charm.

Thanks a lot! 

![Dog says thanks](http://hoodiehq.github.io/hoodie-css/src/content_img/animals/low-profile-dog-1.png)

**Comment by simeydotme** [comment]
No Problem! :) next time I'll see about checking the code out and trying myself... looks like a great app!

**Comment by espy** [comment]
Thanks, feel free!
