### ISSUE TITLE
feat(filter): allow filter by username

### ISSUE THREAD

**Issue by robinboehm** [espy/ubersicht#6]
Extend the applyFilters function / View to allow filtering by username.
https://github.com/espy/ubersicht/blob/gh-pages/script/main.js#L217

Scenario: What are my current tasks in the organisation?

<3

**Comment by janl** [comment]
@robinboehm do you want to work on a patch?

**Comment by robinboehm** [comment]
@janl https://github.com/espy/ubersicht/pull/7
